# Generated by Django 3.0.3 on 2020-08-30 08:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(default='', max_length=200)),
                ('address_line1', models.CharField(default='', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('city', models.CharField(default='', max_length=200)),
                ('state_or_territory', models.CharField(choices=[('1', 'Alabama'), ('2', 'Alaska'), ('3', 'American Samoa'), ('4', 'Arizona'), ('5', 'Arkansas'), ('6', 'California'), ('7', 'Colorado'), ('8', 'Connecticut'), ('9', 'Delaware'), ('10', 'District of Columbia'), ('11', 'Florida'), ('12', 'Georgia'), ('13', 'Guam'), ('14', 'Hawaii'), ('15', 'Idaho'), ('16', 'Illinois'), ('17', 'Indiana'), ('18', 'Iowa'), ('19', 'Kansas'), ('20', 'Kentucky'), ('21', 'Louisiana'), ('22', 'Maine'), ('23', 'Maryland'), ('24', 'Massachusetts'), ('25', 'Michigan'), ('26', 'Minnesota'), ('27', 'Minor Outlying Islands'), ('28', 'Mississippi'), ('29', 'Missouri'), ('30', 'Montana'), ('31', 'Nebraska'), ('32', 'Nevada'), ('33', 'New Hampshire'), ('34', 'New Jersey'), ('35', 'New Mexico'), ('36', 'New York'), ('37', 'North Carolina'), ('38', 'North Dakota'), ('39', 'Northern Mariana Islands'), ('40', 'Ohio'), ('41', 'Oklahoma'), ('42', 'Oregon'), ('43', 'Pennsylvania'), ('44', 'Puerto Rico'), ('45', 'Rhode Island'), ('46', 'South Carolina'), ('47', 'South Dakota'), ('49', 'Tennessee'), ('50', 'Texas'), ('51', 'U.S. Virgin Islands'), ('52', 'Utah'), ('53', 'Vermont'), ('54', 'Virginia'), ('55', 'Washington'), ('56', 'West Virginia'), ('57', 'Wisconsin'), ('58', 'Wyoming')], default='', max_length=40)),
                ('zipcode', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('fax', models.IntegerField(blank=True, default=0, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='', max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state_or_territory', models.CharField(choices=[('1', 'Alabama'), ('2', 'Alaska'), ('3', 'American Samoa'), ('4', 'Arizona'), ('5', 'Arkansas'), ('6', 'California'), ('7', 'Colorado'), ('8', 'Connecticut'), ('9', 'Delaware'), ('10', 'District of Columbia'), ('11', 'Florida'), ('12', 'Georgia'), ('13', 'Guam'), ('14', 'Hawaii'), ('15', 'Idaho'), ('16', 'Illinois'), ('17', 'Indiana'), ('18', 'Iowa'), ('19', 'Kansas'), ('20', 'Kentucky'), ('21', 'Louisiana'), ('22', 'Maine'), ('23', 'Maryland'), ('24', 'Massachusetts'), ('25', 'Michigan'), ('26', 'Minnesota'), ('27', 'Minor Outlying Islands'), ('28', 'Mississippi'), ('29', 'Missouri'), ('30', 'Montana'), ('31', 'Nebraska'), ('32', 'Nevada'), ('33', 'New Hampshire'), ('34', 'New Jersey'), ('35', 'New Mexico'), ('36', 'New York'), ('37', 'North Carolina'), ('38', 'North Dakota'), ('39', 'Northern Mariana Islands'), ('40', 'Ohio'), ('41', 'Oklahoma'), ('42', 'Oregon'), ('43', 'Pennsylvania'), ('44', 'Puerto Rico'), ('45', 'Rhode Island'), ('46', 'South Carolina'), ('47', 'South Dakota'), ('49', 'Tennessee'), ('50', 'Texas'), ('51', 'U.S. Virgin Islands'), ('52', 'Utah'), ('53', 'Vermont'), ('54', 'Virginia'), ('55', 'Washington'), ('56', 'West Virginia'), ('57', 'Wisconsin'), ('58', 'Wyoming')], max_length=40)),
                ('zipcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state_or_territory', models.CharField(choices=[('1', 'Alabama'), ('2', 'Alaska'), ('3', 'American Samoa'), ('4', 'Arizona'), ('5', 'Arkansas'), ('6', 'California'), ('7', 'Colorado'), ('8', 'Connecticut'), ('9', 'Delaware'), ('10', 'District of Columbia'), ('11', 'Florida'), ('12', 'Georgia'), ('13', 'Guam'), ('14', 'Hawaii'), ('15', 'Idaho'), ('16', 'Illinois'), ('17', 'Indiana'), ('18', 'Iowa'), ('19', 'Kansas'), ('20', 'Kentucky'), ('21', 'Louisiana'), ('22', 'Maine'), ('23', 'Maryland'), ('24', 'Massachusetts'), ('25', 'Michigan'), ('26', 'Minnesota'), ('27', 'Minor Outlying Islands'), ('28', 'Mississippi'), ('29', 'Missouri'), ('30', 'Montana'), ('31', 'Nebraska'), ('32', 'Nevada'), ('33', 'New Hampshire'), ('34', 'New Jersey'), ('35', 'New Mexico'), ('36', 'New York'), ('37', 'North Carolina'), ('38', 'North Dakota'), ('39', 'Northern Mariana Islands'), ('40', 'Ohio'), ('41', 'Oklahoma'), ('42', 'Oregon'), ('43', 'Pennsylvania'), ('44', 'Puerto Rico'), ('45', 'Rhode Island'), ('46', 'South Carolina'), ('47', 'South Dakota'), ('49', 'Tennessee'), ('50', 'Texas'), ('51', 'U.S. Virgin Islands'), ('52', 'Utah'), ('53', 'Vermont'), ('54', 'Virginia'), ('55', 'Washington'), ('56', 'West Virginia'), ('57', 'Wisconsin'), ('58', 'Wyoming')], max_length=40)),
                ('zipcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('email', models.CharField(max_length=200)),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
