# Generated by Django 3.0.3 on 2020-08-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesters',
            name='state_or_territory',
            field=models.CharField(choices=[('1', 'Alabama'), ('2', 'Alaska'), ('3', 'American Samoa'), ('4', 'Arizona'), ('5', 'Arkansas'), ('6', 'California'), ('7', 'Colorado'), ('8', 'Connecticut'), ('9', 'Delaware'), ('10', 'District of Columbia'), ('11', 'Florida'), ('12', 'Georgia'), ('13', 'Guam'), ('14', 'Hawaii'), ('15', 'Idaho'), ('16', 'Illinois'), ('17', 'Indiana'), ('18', 'Iowa'), ('19', 'Kansas'), ('20', 'Kentucky'), ('21', 'Louisiana'), ('22', 'Maine'), ('23', 'Maryland'), ('24', 'Massachusetts'), ('25', 'Michigan'), ('26', 'Minnesota'), ('27', 'Minor Outlying Islands'), ('28', 'Mississippi'), ('29', 'Missouri'), ('30', 'Montana'), ('31', 'Nebraska'), ('32', 'Nevada'), ('33', 'New Hampshire'), ('34', 'New Jersey'), ('35', 'New Mexico'), ('36', 'New York'), ('37', 'North Carolina'), ('38', 'North Dakota'), ('39', 'Northern Mariana Islands'), ('40', 'Ohio'), ('41', 'Oklahoma'), ('42', 'Oregon'), ('43', 'Pennsylvania'), ('44', 'Puerto Rico'), ('45', 'Rhode Island'), ('46', 'South Carolina'), ('47', 'South Dakota'), ('49', 'Tennessee'), ('50', 'Texas'), ('51', 'U.S. Virgin Islands'), ('52', 'Utah'), ('53', 'Vermont'), ('54', 'Virginia'), ('55', 'Washington'), ('56', 'West Virginia'), ('57', 'Wisconsin'), ('58', 'Wyoming')], default='', max_length=40),
        ),
    ]
